name: Lint Agente y MCP

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'AgentBancolombia/**'
      - 'McpServerBancolombia/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'AgentBancolombia/**'
      - 'McpServerBancolombia/**'

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v5

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Validación de sintaxis y Linter básico
        run: |
          pip install flake8
          # Falla si hay errores críticos de sintaxis en el Agente o el Servidor MCP
          flake8 AgentBancolombia/ McpServerBancolombia/ -v --count --select=E9,F63,F7,F82 --show-source --statistics